#[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "probe-rs run --chip RP2040"

[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+

[target.thumbv6m-none-eabi]
runner = "elf2uf2-rs -d"
#runner = 'probe-rs run --chip RP235x --verify --protocol swd'

[env]
#DEFMT_LOG = "debug"
LOG_LEVEL = "Info"
