[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
axum = { version = "0.6.20", features = [ "form", "headers", "macros" ] }
chrono = { version = "0.4.31", features = [ "serde", "rkyv" ] }
image = "0.24.7"
postcard = "1.0.8"
rgb565 = "0.1.3"
rpi-messages-common = { path = "../common" }
serde = "1.0.189"
serde_json = "1.0.107"
tokio = { version = "1.33.0", features = [ "macros", "net", "io-util" ] }
