[package]
name = "rpi-messages-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_arch = "arm")'.dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
postcard = "1.0.7"

[target.'cfg(not(target_arch = "arm"))'.dependencies]
serde = { version = "1.0", features = ["derive"] }

